# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/Reception.proto

require 'google/protobuf'


descriptor_data = "\n\x16Protos/Reception.proto\x12\x11QS.ErrorReporting\"\xf7\x01\n\x12SubmitErrorRequest\x12)\n\x04user\x18\x01 \x01(\x0b\x32\x1b.QS.ErrorReporting.UserInfo\x12\'\n\x03\x61pp\x18\x02 \x01(\x0b\x32\x1a.QS.ErrorReporting.AppInfo\x12+\n\x02\x64\x62\x18\x03 \x01(\x0b\x32\x1f.QS.ErrorReporting.DatabaseInfo\x12,\n\x06report\x18\x04 \x01(\x0b\x32\x1c.QS.ErrorReporting.ErrorInfo\x12\x32\n\x0breport_type\x18\x05 \x01(\x0e\x32\x1d.QS.ErrorReporting.ReportType\"\'\n\x08UserInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"Z\n\x07\x41ppInfo\x12\x14\n\x0cproduct_code\x18\x01 \x01(\r\x12\x14\n\x0cmodification\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\tJ\x04\x08\x02\x10\x03R\x0cproduct_name\"\x1c\n\x0c\x44\x61tabaseInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\"X\n\tErrorInfo\x12\x13\n\x0bstack_trace\x18\x01 \x01(\t\x12\x18\n\x10user_description\x18\x02 \x01(\t\x12\x0b\n\x03log\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x15\n\x13SubmitErrorResponse*T\n\nReportType\x12\x14\n\x10REPORT_TYPE_USER\x10\x00\x12\x19\n\x15REPORT_TYPE_AUTOMATIC\x10\x01\x12\x15\n\x11REPORT_TYPE_KNOWN\x10\x02\x32i\n\tReception\x12\\\n\x0bSubmitError\x12%.QS.ErrorReporting.SubmitErrorRequest\x1a&.QS.ErrorReporting.SubmitErrorResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module QS
  module ErrorReporting
    SubmitErrorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QS.ErrorReporting.SubmitErrorRequest").msgclass
    UserInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QS.ErrorReporting.UserInfo").msgclass
    AppInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QS.ErrorReporting.AppInfo").msgclass
    DatabaseInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QS.ErrorReporting.DatabaseInfo").msgclass
    ErrorInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QS.ErrorReporting.ErrorInfo").msgclass
    SubmitErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QS.ErrorReporting.SubmitErrorResponse").msgclass
    ReportType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QS.ErrorReporting.ReportType").enummodule
  end
end
