# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/BackendEmailSender.proto

require 'google/protobuf'


descriptor_data = "\n\x1fProtos/BackendEmailSender.proto\x12\x0eQS.Cloud.Email\"J\n\x17SendEmailBackendRequest\x12/\n\x08messages\x18\x01 \x03(\x0b\x32\x1d.QS.Cloud.Email.OutgoingEmail\"C\n\rOutgoingEmail\x12\x15\n\remail_address\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"+\n\x18SendEmailBackendResponse\x12\x0f\n\x07results\x18\x01 \x01(\t2t\n\x12\x42\x61\x63kendEmailSender\x12^\n\tSendEmail\x12\'.QS.Cloud.Email.SendEmailBackendRequest\x1a(.QS.Cloud.Email.SendEmailBackendResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module QS
  module Cloud
    module Email
      SendEmailBackendRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QS.Cloud.Email.SendEmailBackendRequest").msgclass
      OutgoingEmail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QS.Cloud.Email.OutgoingEmail").msgclass
      SendEmailBackendResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QS.Cloud.Email.SendEmailBackendResponse").msgclass
    end
  end
end
